# Generated by Django 2.1.5 on 2019-05-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_id',
            field=models.IntegerField(),
        ),
    ]
