# Generated by Django 2.2 on 2019-05-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190516_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='table_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
